### ISSUE TITLE
How to get started doc

### ISSUE THREAD

**Issue by bjdevil21** [bobbyrne01/http-tool-firefox#7]
I installed the addon, but there was no UI change in Firefox I could find to get to anything that looked like the screenshot of this addon's UI. How do you access this tool? Can you put those instructions in the README?

**Comment by bobbyrne01** [comment]
hey @bjdevil21 after install there should be a new button like this ..

![selection_004](https://cloud.githubusercontent.com/assets/1746110/9047744/c6217c18-3a2b-11e5-8c10-be069d588f05.png)

If its not there could you try `tools -> customize`? It might be in there and you can drag it onto UI

**Comment by bjdevil21** [comment]
LOL - Didn't see that button up there... Works fine - simple + clean. Thanks for the quick response and the addon! :)

**Comment by bobbyrne01** [comment]
your welcome :+1:
